name: chat-app-backend-test
services:
  server:
    environment:
      - NODE_ENV=test
      - JWT_SECRET=testsecret
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat-app-db
      - POSTGRES_PORT=5432
    build:
      target: test
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
